# Generated by Django 5.0.1 on 2025-11-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('moq', models.CharField(help_text='Minimum Order Quantity', max_length=100)),
                ('packaging', models.CharField(max_length=200)),
                ('badge', models.CharField(blank=True, help_text="e.g., 'Bestseller', 'New', 'Organic'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(choices=[('Wheat', 'Wheat'), ('Snowflake', 'Snowflake'), ('Box', 'Box'), ('Leaf', 'Leaf'), ('Package', 'Package'), ('ShoppingBasket', 'Shopping Basket')], max_length=50)),
                ('secondary_icon_name', models.CharField(choices=[('Wheat', 'Wheat'), ('Snowflake', 'Snowflake'), ('Box', 'Box'), ('Leaf', 'Leaf'), ('Package', 'Package'), ('ShoppingBasket', 'Shopping Basket')], max_length=50)),
                ('gradient', models.CharField(help_text="e.g., 'from-amber-500 to-orange-600'", max_length=100)),
                ('bg_gradient', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='verticals/')),
                ('button_color', models.CharField(max_length=100)),
                ('button_text', models.CharField(default='REQUEST QUOTE', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='api.vertical'),
        ),
        migrations.CreateModel(
            name='VerticalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.vertical')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
