# Generated by Django 5.0.1 on 2025-11-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Westend Corporation', max_length=200)),
                ('tagline', models.CharField(default='Premium Food Products', max_length=200)),
                ('founded_year', models.IntegerField(default=2010)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('headquarters', models.CharField(default='Delhi, India', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(choices=[('Award', 'Award'), ('Users', 'Users'), ('TrendingUp', 'Trending Up'), ('Heart', 'Heart'), ('Package', 'Package'), ('CheckCircle', 'Check Circle'), ('Shield', 'Shield'), ('Star', 'Star')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
