# Generated by Django 5.0.1 on 2025-11-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyinfo_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=20),
        ),
    ]
