# Generated by Django 5.0.1 on 2025-11-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Westend Organic', help_text='Brand name', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.CharField(blank=True, help_text="e.g., 'FSSAI, Organic India, USDA'", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Product features, one per line'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Second product image', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Third product image', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='India', help_text='Country or region of origin', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(default='12 Months', help_text='Product shelf life', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default='Cool & Dry Place', help_text='Storage instructions', max_length=200),
        ),
    ]
