# Generated by Django 5.0.1 on 2025-11-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_featured_products'),
        ('api', '0004_product_brand_product_certifications_and_more'),
    ]

    operations = [
    ]
