# Generated by Django 5.0.1 on 2025-11-22 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20251120_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('products', 'Products Page'), ('product_detail', 'Product Detail'), ('about', 'About Page'), ('contact', 'Contact Page')], max_length=50)),
                ('action', models.CharField(choices=[('page_view', 'Page View'), ('quote_request', 'Quote Request'), ('contact_form', 'Contact Form'), ('product_view', 'Product View')], default='page_view', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['page'], name='api_pagevis_page_6848ec_idx'), models.Index(fields=['action'], name='api_pagevis_action_08ff39_idx'), models.Index(fields=['timestamp'], name='api_pagevis_timesta_ac6d64_idx')],
            },
        ),
    ]
