# Generated by Django 5.0.1 on 2025-11-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pagevisit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagevisit',
            new_name='api_pagevis_page_idx',
            old_name='api_pagevis_page_6848ec_idx',
        ),
        migrations.RenameIndex(
            model_name='pagevisit',
            new_name='api_pagevis_action_idx',
            old_name='api_pagevis_action_08ff39_idx',
        ),
        migrations.RenameIndex(
            model_name='pagevisit',
            new_name='api_pagevis_timestamp_idx',
            old_name='api_pagevis_timesta_ac6d64_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
