# Generated by Django 5.0.1 on 2025-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Full name of the reviewer', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text="Reviewer's company (optional)", max_length=200)),
                ('position', models.CharField(blank=True, help_text="Job title (e.g., 'Purchasing Manager')", max_length=200)),
                ('country', models.CharField(blank=True, help_text="Country (e.g., 'USA', 'Canada')", max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Star rating (1-5)')),
                ('review_text', models.TextField(help_text='Full review/testimonial text')),
                ('is_verified', models.BooleanField(default=False, help_text='Mark as verified customer')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Publish this review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Review',
                'verbose_name_plural': 'Business Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='api_review_rating_idx'), models.Index(fields=['is_active'], name='api_review_active_idx'), models.Index(fields=['is_featured'], name='api_review_featured_idx')],
            },
        ),
    ]
