# Generated by Django 5.0.1 on 2025-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_heroslide_delete_businessreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSlide',
        ),
        migrations.AddField(
            model_name='vertical',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Image to display in hero section carousel (recommended: 1920x600px)', null=True, upload_to='verticals/hero/'),
        ),
    ]
