# Generated by Django 5.0.1 on 2025-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_heroslide_vertical_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title/headline', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300)),
                ('image', models.ImageField(help_text='Recommended: 1920x500px', upload_to='hero_slides/')),
                ('link_text', models.CharField(blank=True, help_text='Button text (optional)', max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='Button link (optional)', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='vertical',
            name='hero_image',
        ),
    ]
