# Generated by Django 5.0.1 on 2025-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('products', 'Products Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('certifications', 'Certifications Page')], help_text='Select page for background', max_length=50, unique=True)),
                ('background_image', models.ImageField(help_text='Recommended: 1920x1080px. Will be auto-optimized.', upload_to='page_backgrounds/')),
                ('opacity', models.FloatField(default=0.08, help_text='Background opacity: 0.0 (invisible) to 1.0 (fully visible)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this background')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Background',
                'verbose_name_plural': 'Page Backgrounds',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='SectionBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('category_showcase', 'Category Showcase'), ('featured_products', 'Featured Products'), ('why_choose_us', 'Why Choose Us'), ('certifications', 'Certifications Section')], help_text='Select section for background', max_length=50, unique=True)),
                ('background_image', models.ImageField(help_text='Recommended: 1920x600px. Will be auto-optimized.', upload_to='section_backgrounds/')),
                ('opacity', models.FloatField(default=0.05, help_text='Background opacity: 0.0 (invisible) to 1.0 (fully visible)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this background')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Background',
                'verbose_name_plural': 'Section Backgrounds',
                'ordering': ['section'],
            },
        ),
    ]
