# Generated by Django 5.0.1 on 2025-12-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pagebackground_sectionbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Company logo image (PNG/JPG). Recommended: 500x500px with transparent background.', null=True, upload_to='company/logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo_video',
            field=models.FileField(blank=True, help_text='Company logo video (MP4/WebM). Max 5MB. Recommended: 500x500px, short loop.', null=True, upload_to='company/logos/videos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='use_video_logo',
            field=models.BooleanField(default=False, help_text='If enabled and video is uploaded, video logo will be displayed instead of image.'),
        ),
    ]
