# Generated by Django 5.0.1 on 2025-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_companyinfo_logo_image_companyinfo_logo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='use_video',
            field=models.BooleanField(default=False, help_text='Use video instead of image'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='Hero video (MP4 recommended)', null=True, upload_to='hero_videos/'),
        ),
    ]
