# Generated by Django 5.0.1 on 2025-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_heroslide_use_video_heroslide_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='Optional: Video background (MP4)', null=True, upload_to='hero_videos/'),
        ),
    ]
