# Generated by Django 5.0.1 on 2025-12-04 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_heroslide_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Category name (e.g., 'Punjabi Jaggery')", max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name', max_length=50)),
                ('bg_color', models.CharField(default='#1e293b', help_text='Header background color (hex)', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show in sidebar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Subcategory name (e.g., 'Pesi Jaggery')", max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True, help_text='Show in sidebar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.productcategory')),
                ('products', models.ManyToManyField(blank=True, help_text='Link to products', related_name='sidebar_subcategories', to='api.product')),
            ],
            options={
                'verbose_name': 'Product Subcategory',
                'verbose_name_plural': 'Product Subcategories',
                'ordering': ['order', 'title'],
            },
        ),
    ]
