# Generated by Django 5.0.1 on 2025-12-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_productcategory_productsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='products',
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='title',
            field=models.CharField(help_text="Product name (e.g., 'Pesi Jaggery')", max_length=200),
        ),
    ]
