# Generated by Django 5.0.1 on 2025-12-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_productsubcategory_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Brochure title (e.g., 'Product Catalog 2024')", max_length=200)),
                ('file', models.FileField(help_text='PDF file', upload_to='brochures/')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website. Only the most recent active one will be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brochure',
                'verbose_name_plural': 'Brochures',
                'ordering': ['-created_at'],
            },
        ),
    ]
