# Generated by Django 5.0.1 on 2025-12-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_brochure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'ordering': ['id'], 'verbose_name_plural': 'Company Info'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this product from the website (it will still appear in the PDF Catalog).'),
        ),
    ]
