# Generated by Django 5.0.1 on 2025-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_companyinfo_options_product_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.CharField(default='support@westendcorporation.in', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='+91 93119 33481', max_length=50),
        ),
    ]
