#!/bin/bash

echo "🔄 Clearing browser cache and localStorage..."
echo ""
echo "Please follow these steps to clear the chatbot session:"
echo ""
echo "1. Open your website: https://westendcorporation.in"
echo "2. Open Developer Tools (F12 or Ctrl+Shift+I)"
echo "3. Go to Console tab"
echo "4. Copy and paste this command:"
echo ""
echo "localStorage.removeItem('chatbot_session_id');"
echo "location.reload();"
echo ""
echo "5. Press Enter"
echo ""
echo "Or open the debug page:"
echo "https://westendcorporation.in/debug-chat.html"
echo ""
echo "This will clear the old session and force a fresh start."
