
import os
import django
from django.db.models import Q

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from api.models import Product, Vertical
from django.core.files import File

# Full list from user (same source as before)
raw_list = """
FANTA CAN
LIMCA CAN
THUMS UP CAN
FANTA GLASS BOTTLE
MAZZA GLASS BOTTLE
THUMS UP GLASS BOTTLE
LIMCA GLASS BOTTLE
FANTA PET BOTTEL (1 LTR, 750 ML, 2 LTR)
LIMCA PET BOTTEL (1 LTR, 750 ML, 2 LTR)
THUMS UP PET BOTTEL (1 LTR, 750 ML, 2 LTR)
CAMPA COLA
CAMPA LEMON
CAMPA ORANGE
APPY FIZZ (1 LTR, 600 ML)
FROOTI (125 ML, 1.2 LTR, 600 ML)
JALANI NIMBU PANI
JALANI AAM PANNA
KASHMIRA MALA JEERA CAN
KASHMIRA GLASS BOTTEL
LAHORI JEERA DRINK (300 ML, 160 ML)
KANCHAZ LEMON DRINKS
KANCHAZ SHIKANJI DRINKS
KANCHAZ KACHA AAM DRINKS
KANCHAZ MINT MOJITO DRINKS
KASMIRA JEERA DRINK CAN/GLASS BTL
RUBY PEDHA SWEET
KISSAN MIX FRUIT JAM (1 KG, 500 GM)
KISSAN JAM PINEAPPLE (1 KG, 500 GM)
KISSAN JAM MANGO (1 KG, 500 GM)
KISSAN JAM ORANGE (1 KG)
ENO LEMON (100 GM, SACHETS)
ENO REGULAR
ENO ORANGE
MAGGI MASALA NOODLES (LAGE PACK, 70 GM, 420 GM)
MAGGI HOT & SWEET SAUCE
KISSAN TOMATO KETCHUP BOTTLE
MAGGI MASALA (6 GM, 200 GM)
ROOHAFAZA SHARBAT
CHINGS HAKKA NOODLES
CHINGS SAUCE GREEN CHILLY
CHINGS SAUCE RED CHILLY
CHINGS SAUCE DARK SOY
CHINGS SHEZWAN CHUTNY
NESTLE MAHA MUNCH CHOCOLATE
PULSE KACHHA AAM CANDY JAR
LONDONDERRY TOFFEE
MELODY CHOCOLATY TOFFEE
SHADANI COCONUT PEDA
SHADANI COCONUT SWEET
SHADANI PAAN MIX SAUNF
SHADANI IMLI BITE
SHADANI CHATPTA AMLA CANDY
SHADANI CHATPATI CANDY CAN
SHADANI MIX FRUIT CANDY CAN
SHADANI PAAN CANDY CAN
SHADANI MANGO CANDY CAN
SHADANI LEMON CANDY CAN
SHADANI BLACK CURRENT CANDY CAN
SHADANI LITCHI CANDY CAN
SHADANI KACHA AAM CANDY CAN
SHADANI SWEET IMLI CANDY CAN
SHADANI FRUIT JELLY CAN
SHADANI ANARDANA GOLI CAN
SHADANI KHATTA MEETHA AAMPAK CAN
SHADANI RAM LADOO CAN
SHADANI HING PEDA CAN
SHADANI IMLI BOOTA CAN
SHADANI CHATPATA AMLA CAN
SHADANI AJWAIN PACHAK CAN
SHADANI JELLY JELLY CAN
SHADANI KALA KHATTA CAN
SHADANI MANGO BITE CAN
SHADANI MADRASI SAUNF CAN
SHADANI PLAIN MIX SAUNF CAN
SHADANI ROASTED SPECIAL SAUNF CAN
SHADANI CHENNAI SAUNF CAN
RINKAS MANGO CANDY JAR
RINKAS CHATMOLA CANDY JAR/GOLI JAR/POUCH
RINKAS COLA CANDY JAR
RINKAS ORANGE CANDY JAR
RINKAS LICHI CANDY JAR
RINKAS MIX FRUIT CANDY JAR
RINKAS KACHI KERY CANDY JAR
RINKAS AAM PAPAD JAR
RINKAS IMLI JELLY BAR JAR
SWEET KHEEL
PLAIN KHEEL + PATASHA IN JAR
BINGO MAD ANGLE (MASALA, CHESSES NACHOS, TOMATO MADNESS, ACHARI MASTI, CHAT, PIZZA)
BINGO TEDHE MEDHE
KURKURE (MASALA MUNCH, SOLID MASTI, RED CHILLI CHATAKA, GREEN CHUTNEY)
LAYS (AMERICAN STYLE CREAM & ONION, WEST INDIES HOT & SWEET CHILLI, SPANISH TOMATO TANGO, CLASIC SALTED, MAGIC MASALA, CHILLLI LEMON, MAX MACHO CHILLI)
UNCLE CHIPS SPICY TREAT
DIAMOND CHIPS (CREAM N ONION, MAGIC MASALA, TOM-CHI, CLASIC SALTED, PlAIN SALTED, PIRI PIRI)
CHAND TARA
LAL JUBAN CHURAN STICK
KAALA JADOO CHURAN STICK
ROSTED MAKHANA (PUDINA POP, HIMALAYAN SALT, PERI PERI, CHEES HERBS)
SOHNA MANGO PICKLES
SOHNA MIX PIKLES
SOHNA CHILLI PICKLES
MDH DEGGI MIRCH PWD (100 GM, 500 GM)
MDH CHAT MSL / CHUNKY CHAAT MASALA
MDH KITCHEN KING MSL (100 GM, 500 GM)
MDH GARAM MSL (100 GM, 500 GM)
MDH MEAT MSL (100 GM, 500 GM)
MDH CHICKEN MSL
MDH PAV BHAJI MSL
MDH RAJMAH MSL
MDH DAL MAKHNI MSL
MDH PANI PURI MSL
MDH SAMBER MSL
MDH CHANNA MASALA
EVEREST TEA MASALA
EVEREST CHOLE MASALA
EVEREST CHAT MASALA
EVEREST RAJMAAH MASALA
EVEREST MEAT MASALA
EVEREST PAV BHAJI MASALA
EVEREST GARAM MASALA
EVEREST SAMBHAR MASALA
KNORR SOUP (HOT & SWEET, HOT & SOUR VEG, MIX VEG, THICK TOMATO, SWEET CORN VEG/CHICKEN, MANCHOW SOUP, ITALIAN, MAXICON)
PATANJALI AMLA MURABBA
PATANJALI ALOVERA JUICE
PATANJALI AMLA JUICE
PATANJALI SPECIAL CHYANWANPRASH WITH SAFFRON
VEEBA SAUCE
PACHRANGA AMLA MURABBA JAR
PACHRANGA CARROT MURABBA PJ JAR
PACHRANGA APPLE MURABBA JAR
PACHRANGA TURNIP CAULIFLOWER CARROT
PACHRANGA MANGO UNPEELED/PEELES
PACHRANGA MIX PICKLE
PACHRANGA RED CHILLI STUFFED
PACHRANGA AMLA PICKLE PLASTIC JAR
BAMBINO VERMICELLI (400 GM, 800 GM, ROSTED)
ANIL VERMICELLI
ANIL RAGI VERMICELLI
HORLICKS (CHOCOLATE, ELACHI, KESAR BADAM, LITE, MOTHER)
BOOST POWDER
COMPLAN (CHOCOLATE FLAVOUR, KESAR BADAM FLAVOUR)
AAM GOLI CAN
SHODHY HARAD CAN
DHANNA DAL CAN
SUPER MIX CAN
MADHUR CHURAN CONT
COCONUT LADDU CAN
PAN GULKAND JAR
DRY PAN JAR
JHILMIL SUPARI CONT (W/O SUPARI)
MITH PAN CHURAN JAR
KASHMIRI MIX CAN (W/O SUPARI)
GREEN MUKHWASH CAN
BANASARI PAN JAR (W/O SUPARI)
CALCUTTA PAN JAR
ROYAL OLYMPIC MUKHWAS CAN
SUGAR COATED SONFF CAN
MADRASI SONFF( WHITE) CAN
MADRASI SONFF( GREEN) CAN
APLAM CHAPLAM CAN
ANARDANA GOLI CAN
IMLI LADOO (MODAK) CAN
MANCHALI IMLI CAN
HAZMA HAZAM CAN
AMLA PACHAK CAN
THANDA MITHA PAN GULKAND JAR
CHINGS SINGAPORE NOODLES
TOP RAMEN MASALA NOODLES
TOP RAMEN CURRY NOODLES
YIPPEE MAGIC MSL NOODLES
LIJJAT UDAD PAPAD (VARIOUS TYPES: WITH PAPPER, GREEN CHILLI, RED CHILLI, PLAIN, JEERA, SPECIAL)
LIJJAT MOONG PAPAD (PLAIN, WITH PEPPER, SPECIAL)
LIJJAT PUNJABI MASALA SPECIAL PAPAD
LIJJAT UDADA SINDHI MASALA SPECIAL PAPAD
LIJJAT DHAMTA SPECIAL PAPAD
TOO YUMM (MGC DP CHAAT, TANGY TOMATO, VS CHILLI CHATAKA, SOUR CREAM & ONION, CHIPS INDIAN MASALA, CHIPS SPANISH TOMATO, KARARE CHILLI ACHARI, KARARE MUNCHY MASALA, KARARE NOODLE MASALA, PS ALOO CHAAT, CHIPS ASCO)
CORNITOS TACO SHELL (4", 6")
CORNITOS COATED GREEN PEAS (SWABI, HOT & SPICE)
CORNITOS ROSTED PEANUTS SALTED
CORNITOS PARTY MIX
CORNITOS ROSTED PUMPKIN SEEDS SALTED
CORNITOS SUNFLOWER SEEDS NATURAL
CORNITOS CORN NUT (LEMON CHILLI CILANTRO, CHEESY JALAPENO)
CORNITOS SUPER SEED (MIX SEED)
CHIPS/WAFERS SAUCY TOMATO
CHIPS/WAFERS PUDINA JALJIRA
DABUR ACTIVE BLOOD PURIFIER
DABUR CHAWANPRASH (SUGER FREE & regular)
ROASTED CHANA (WITH/WITHOUT SKIN, HINGH CHANA, LEMON FLAVOUR, TURMERIC CHANA, BOMBAY MASALA CHANA)
PHOOL MAKHANA
NUTELLA SOYA CHUNKS
SOYA CHUNK MINI
SOYA CHUNK BIG
MARUNDA GACHAK
FINGER JACHAK
BODHI GACHAK
DOUBLE PATTI GACHAK
PEANUT GACHAK
GUR REWARI
SUGAR REWARI
RAJGIRI LADOO
PANJABI WADI
ANGOORI PETHA
BOONDI
"""

vertical, _ = Vertical.objects.get_or_create(title="Processed Foods")
placeholder_path = '/var/www/westend-Corporation/backend/media/products/placeholder.jpg'

count_missing = 0
for line in raw_list.strip().split('\n'):
    line = line.strip().replace('•', '').strip()
    if not line:
        continue
        
    # Check if exists (case insensitive)
    # Also check if it might have been modified slightly
    if not Product.objects.filter(name__iexact=line).exists():
        print(f"MISSING: {line} -> Adding now...")
        
        product = Product(
            name=line,
            vertical=vertical,
            description=f"Premium quality {line}. Authentic taste and finest ingredients.",
            moq="1 Case",
            packaging="Standard Packaging",
            stock_status="in_stock",
            origin="India",
            shelf_life="12 Months",
            brand="Westend Selection",
            is_active=True
        )
        
        # Use placeholder if available
        if os.path.exists(placeholder_path):
            with open(placeholder_path, 'rb') as f:
                product.image.save('placeholder.jpg', File(f), save=False)
                product.save()
        else:
             # Just save without image if placeholder missing (should not happen based on context)
             product.save()
        
        count_missing += 1
    else:
        # Product exists
        pass

if count_missing == 0:
    print("All products in the list are present in the database!")
else:
    print(f"Successfully restored {count_missing} missing products.")
